entities_config:
    Oro\Bundle\TestFrameworkBundle\Entity\Item:
        flexible_manager:     search_item_manager
        flexible_class:       Oro\Bundle\TestFrameworkBundle\Entity\Item
        flexible_value_class: Oro\Bundle\TestFrameworkBundle\Entity\ItemValue
